register/urls.py
import django

from django.conf.urls import url
from django.conf.urls import include
from django.conf import settings
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth import views as auth_views

from django.views.generic.base import TemplateView

from .views import ActivationView
from .views import RegistrationView
from .views import ResendActivationView

app_name="register"
urlpatterns = [
        url(r'^login/$',
            auth_views.LoginView.as_view(
                template_name='registration/login.html'),
            name='auth_login'),
        url(r'^logout/$',
            auth_views.LogoutView.as_view(
                template_name='registration/logout.html'),
            name='auth_logout'),
        url(r'^password/change/$',
            auth_views.PasswordChangeView.as_view(
                success_url=reverse_lazy('register:auth_password_change_done')),
            name='auth_password_change'),
        url(r'^password/change/done/$',
            auth_views.PasswordChangeDoneView.as_view(),
            name='auth_password_change_done'),
        url(r'^password/reset/$',
            auth_views.PasswordResetView.as_view(
                success_url=reverse_lazy('register:auth_password_reset_done')),
            name='auth_password_reset'),
        url(r'^password/reset/complete/$',
            auth_views.PasswordResetCompleteView.as_view(),
            name='auth_password_reset_complete'),
        url(r'^password/reset/done/$',
            auth_views.PasswordResetDoneView.as_view(),
            name='auth_password_reset_done'),
        url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
            auth_views.PasswordResetConfirmView.as_view(
                success_url=reverse_lazy('register:auth_password_reset_complete')),
            name='auth_password_reset_confirm'),
        url(r'^activate/complete/$',
            TemplateView.as_view(template_name='registration/activation_complete.html'),
            name='registration_activation_complete'),
        url(r'^activate/resend/$',
            ResendActivationView.as_view(),
            name='registration_resend_activation'),
        # Activation keys get matched by \w+ instead of the more specific
        # [a-fA-F0-9]{40} because a bad activation key should still get to the view;
        # that way it can return a sensible "invalid key" message instead of a
        # confusing 404.
        url(r'^activate/(?P<activation_key>\w+)/$',
            ActivationView.as_view(),
            name='registration_activate'),
        url(r'^register/complete/$',
            TemplateView.as_view(template_name='registration/registration_complete.html'),
            name='registration_complete'),
        url(r'^register/closed/$',
            TemplateView.as_view(template_name='registration/registration_closed.html'),
            name='registration_disallowed'),
    ]
    
if getattr(settings, 'INCLUDE_REGISTER_URL', True):
    urlpatterns += [
        url(r'^register/$',
            RegistrationView.as_view(),
            name='registration_register'),
    ]

register/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.


import datetime
import hashlib
import re
import string

from django.conf import settings
from django.core.exceptions import ImproperlyConfigured
from django.core.exceptions import ObjectDoesNotExist
from django.core.mail import EmailMultiAlternatives
from django.db import models, transaction
from django.template import TemplateDoesNotExist
from django.template.loader import render_to_string
from django.utils.crypto import get_random_string
from django.utils.encoding import python_2_unicode_compatible
from django.utils.timezone import now as datetime_now
from django.utils.translation import ugettext_lazy as _

from .users import UserModel, UserModelString


SHA1_RE = re.compile('^[a-f0-9]{40}$')



class RegistrationManager(models.Manager):
    """
    Custom manager for the ``RegistrationProfile`` model.

    The methods defined here provide shortcuts for account creation
    and activation (including generation and emailing of activation
    keys), and for cleaning out expired inactive accounts.

    """

    def _activate(self, profile, site, get_profile):
        """
        Activate the ``RegistrationProfile`` given as argument.
        User is able to login, as ``is_active`` is set to ``True``
        """
        user = profile.user
        user.is_active = True
        profile.activated = True

        with transaction.atomic():
            user.save()
            profile.save()
        if get_profile:
            return profile
        else:
            return user

    def activate_user(self, activation_key, site, get_profile=False):
        """
        Validate an activation key and activate the corresponding
        ``User`` if valid.

        If the key is valid and has not expired, return the ``User``
        after activating.

        If the key is not valid or has expired, return ``False``.

        If the key is valid but the ``User`` is already active,
        return ``User``.

        If the key is valid but the ``User`` is inactive, return ``False``.

        To prevent reactivation of an account which has been
        deactivated by site administrators, ``RegistrationProfile.activated``
        is set to ``True`` after successful activation.

        """
        # Make sure the key we're trying conforms to the pattern of a
        # SHA1 hash; if it doesn't, no point trying to look it up in
        # the database.
        if SHA1_RE.search(activation_key):
            try:
                profile = self.get(activation_key=activation_key)
            except self.model.DoesNotExist:
                # This is an actual activation failure as the activation
                # key does not exist. It is *not* the scenario where an
                # already activated User reuses an activation key.
                return False

            if profile.activated:
                # The User has already activated and is trying to activate
                # again. If the User is active, return the User. Else,
                # return False as the User has been deactivated by a site
                # administrator.
                if profile.user.is_active:
                    return profile.user
                else:
                    return False

            if not profile.activation_key_expired():
                return self._activate(profile, site, get_profile)

        return False

    def create_inactive_user(self, site, new_user=None, send_email=True,
                             request=None, profile_info={}, **user_info):
        """
        Create a new, inactive ``User``, generate a
        ``RegistrationProfile`` and email its activation key to the
        ``User``, returning the new ``User``.

        By default, an activation email will be sent to the new
        user. To disable this, pass ``send_email=False``.
        Additionally, if email is sent and ``request`` is supplied,
        it will be passed to the email template.

        """
        if new_user is None:
            password = user_info.pop('password')
            new_user = UserModel()(**user_info)
            new_user.set_password(password)
        new_user.is_active = False

        # Since we calculate the RegistrationProfile expiration from this date,
        # we want to ensure that it is current
        new_user.date_joined = datetime_now()

        with transaction.atomic():
            new_user.save()
            registration_profile = self.create_profile(
                new_user, **profile_info)

        if send_email:
            registration_profile.send_activation_email(site, request)

        return new_user

    def create_profile(self, user, **profile_info):
        """
        Create a ``RegistrationProfile`` for a given
        ``User``, and return the ``RegistrationProfile``.

        The activation key for the ``RegistrationProfile`` will be a
        SHA1 hash, generated from a secure random string.

        """
        profile = self.model(user=user, **profile_info)

        if 'activation_key' not in profile_info:
            profile.create_new_activation_key(save=False)

        profile.save()

        return profile

    def resend_activation_mail(self, email, site, request=None):
        """
        Resets activation key for the user and resends activation email.
        """
        try:
            profile = self.get(user__email__iexact=email)
        except ObjectDoesNotExist:
            return False
        # TODO: Catch multiple objects returned exception?

        if profile.activated or profile.activation_key_expired():
            return False

        profile.create_new_activation_key()
        profile.send_activation_email(site, request)

        return True

    def delete_expired_users(self):
        """
        Remove expired instances of ``RegistrationProfile`` and their
        associated ``User``s.

        Accounts to be deleted are identified by searching for
        instances of ``RegistrationProfile`` with expired activation
        keys, and then checking to see if their associated ``User``
        instances have the field ``is_active`` set to ``False``; any
        ``User`` who is both inactive and has an expired activation
        key will be deleted.

        It is recommended that this method be executed regularly as
        part of your routine site maintenance; this application
        provides a custom management command which will call this
        method, accessible as ``manage.py cleanupregistration``.

        Regularly clearing out accounts which have never been
        activated serves two useful purposes:

        1. It alleviates the ocasional need to reset a
           ``RegistrationProfile`` and/or re-send an activation email
           when a user does not receive or does not act upon the
           initial activation email; since the account will be
           deleted, the user will be able to simply re-register and
           receive a new activation key.

        2. It prevents the possibility of a malicious user registering
           one or more accounts and never activating them (thus
           denying the use of those usernames to anyone else); since
           those accounts will be deleted, the usernames will become
           available for use again.

        If you have a troublesome ``User`` and wish to disable their
        account while keeping it in the database, simply delete the
        associated ``RegistrationProfile``; an inactive ``User`` which
        does not have an associated ``RegistrationProfile`` will not
        be deleted.

        """
        for profile in self.all():
            try:
                if profile.activation_key_expired():
                    user = profile.user
                    if not user.is_active:
                        profile.delete()
                        user.delete()
            except UserModel().DoesNotExist:
                profile.delete()


@python_2_unicode_compatible
class RegProfile(models.Model):
    """
    A simple profile which stores an activation key for use during
    user account registration.

    Generally, you will not want to interact directly with instances
    of this model; the provided manager includes methods
    for creating and activating new accounts, as well as for cleaning
    out accounts which have never been activated.

    While it is possible to use this model as the value of the
    ``AUTH_PROFILE_MODULE`` setting, it's not recommended that you do
    so. This model's sole purpose is to store data temporarily during
    account registration and activation.

    """
    user = models.OneToOneField(
        UserModelString(),
        on_delete=models.CASCADE,
        verbose_name=_('user'),
    )
    activation_key = models.CharField(_('activation key'), max_length=40)
    activated = models.BooleanField(default=False)

    objects = RegistrationManager()

    class Meta:
        verbose_name = _('registration profile')
        verbose_name_plural = _('registration profiles')

    def __str__(self):
        return "Registration information for %s" % self.user

    def create_new_activation_key(self, save=True):
        """
        Create a new activation key for the user
        """
        random_string = get_random_string(length=32, allowed_chars=string.printable)
        self.activation_key = hashlib.sha1(random_string.encode('utf-8')).hexdigest()

        if save:
            self.save()

        return self.activation_key
        
    def activation_key_expired(self):
        """
        Determine whether this ``RegistrationProfile``'s activation
        key has expired, returning a boolean -- ``True`` if the key
        has expired.

        Key expiration is determined by a two-step process:

        1. If the user has already activated, ``self.activated`` will
           be ``True``. Re-activating is not permitted, and so this

register/forms.py
"""
Forms and validation code for user registration.

Note that all of these forms assume Django's bundle default ``User``
model; since it's not possible for a form to anticipate in advance the
needs of custom user models, you will need to write your own forms if
you're using a custom model.

"""
from __future__ import unicode_literals


from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import ugettext_lazy as _

from .users import UserModel, UsernameField

User = UserModel()


class RegistrationForm(UserCreationForm):
    """
    Form for registering a new user account.

    Validates that the requested username is not already in use, and
    requires the password to be entered twice to catch typos.

    Subclasses should feel free to add any additional validation they
    need, but should avoid defining a ``save()`` method -- the actual
    saving of collected user data is delegated to the active
    registration backend.

    """
    required_css_class = 'required'
    email = forms.EmailField(label=_("E-mail"))

    class Meta:
        model = User
        fields = (UsernameField(), "email")


class RegistrationFormUsernameLowercase(RegistrationForm):
    """
    A subclass of :class:`RegistrationForm` which enforces unique case insensitive
    usernames, make all usernames to lower case.

    """
    def clean_username(self):
        username = self.cleaned_data.get('username', '').lower()
        if User.objects.filter(**{UsernameField(): username}).exists():
            raise forms.ValidationError(_('A user with that username already exists.'))

        return username
 
class RegistrationFormTermsOfService(RegistrationForm):
    """
    Subclass of ``RegistrationForm`` which adds a required checkbox
    for agreeing to a site's Terms of Service.

    """
    tos = forms.BooleanField(widget=forms.CheckboxInput,
                             label=_('I have read and agree to the Terms of Service'),
                             error_messages={'required': _("You must agree to the terms to register")})


class RegistrationFormUniqueEmail(RegistrationForm):
    """
    Subclass of ``RegistrationForm`` which enforces uniqueness of
    email addresses.

    """
    bad_domains = ['aim.com', 'aol.com', 'email.com', 'gmail.com',
                   'googlemail.com', 'hotmail.com', 'hushmail.com',
                   'msn.com', 'mail.ru', 'mailinator.com', 'live.com',
                   'yahoo.com']
    def clean_email(self):
        """
        Validate that the supplied email address is unique for the
        site.

        """
        email_domain = self.cleaned_data['email'].split('@')[1]
        if User.objects.filter(email__iexact=self.cleaned_data['email']):
            raise forms.ValidationError(_("This email address is already in use. Please supply a different email address."))
        if email_domain not in self.bad_domains:
            raise forms.ValidationError(_("Please supply a valid email address."))
        return self.cleaned_data['email']


class RegistrationFormNoFreeEmail(RegistrationForm):
    """
    Subclass of ``RegistrationForm`` which disallows registration with
    email addresses from popular free webmail services; moderately
    useful for preventing automated spam registrations.

    To change the list of banned domains, subclass this form and
    override the attribute ``bad_domains``.

    """
    bad_domains = ['aim.com', 'aol.com', 'email.com', 'gmail.com',
                   'googlemail.com', 'hotmail.com', 'hushmail.com',
                   'msn.com', 'mail.ru', 'mailinator.com', 'live.com',
                   'yahoo.com']

    def clean_email(self):
        """
        Check the supplied email address against a list of known free
        webmail domains.

        """
        email_domain = self.cleaned_data['email'].split('@')[1]
        if email_domain in self.bad_domains:
            raise forms.ValidationError(_("Registration using free email addresses is prohibited. Please supply a different email address."))
        return self.cleaned_data['email']


class ResendActivationForm(forms.Form):
    required_css_class = 'required'
    email = forms.EmailField(label=_("E-mail"))

templates/based.html
{% load staticfiles %}
<!doctype html>
<!--[if lt IE 7]>		<html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>			<html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>			<html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!-->	<html class="no-js" lang="en"> <!--<![endif]-->

<!-- Mirrored from wahabali.com/work/tasver/index2.html by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 09 Sep 2017 09:06:03 GMT -->
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="description" content="">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %} SelfieStreak{% endblock %}</title>
	<link rel="apple-touch-icon" href="apple-touch-icon.png">
	<link rel="stylesheet" href="{% static 'css3/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'css3/normalize.css' %}">
	<link rel="stylesheet" href="{% static 'css3/icomoon.css' %}">
	<link rel="stylesheet" href="{% static 'css3/font-awesome.min.css' %}">
	<link rel="stylesheet" href="{% static 'css3/cubeportfolio.css' %}">
	<link rel="stylesheet" href="{% static 'css3/jgallery.min.css' %}">
	<link rel="stylesheet" href="{% static 'css3/pogoslider.css' %}">
	<link rel="stylesheet" href="{% static 'css3/prettyPhoto.css' %}">
	<link rel="stylesheet" href="{% static 'css3/slick-theme.css' %}">
	<link rel="stylesheet" href="{% static 'css3/slick.css' %}">
	<link rel="stylesheet" href="{% static 'css3/transitions.css' %}">
	<link rel="stylesheet" href="{% static 'style.css' %}">
	<link rel="stylesheet" href="{% static 'css3/color.css' %}">
	<link rel="stylesheet" href="{% static 'css3/responsive.css' %}">
	<script src="{% static 'js3/vendor/modernizr-2.8.3-respond-1.4.2.min.js' %}"></script>
	<style>
		.bt-footerborder 
		{
		border:none;
		}
		.g{
			height: 100%;
			width: 100%;
		}
			</style>
	{% block style %}
<!--	<style>
		html,body{
			padding: 0px;
			margin: 0px;
position: static;
height:  auto;
		}
	</style> -->
			{% endblock %}
</head>
<body "page-template-default wpb-js-composer js-comp-ver-5.1.1 vc_responsive">
	<!--[if lt IE 8]>
		<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
	<![endif]-->
	<!--************************************
			PreLoader Start
	*************************************-->
	<div id="bt-preloader"><div class="bt-preloadericon"></div></div>
	<!--************************************
			PreLoader End
    *************************************-->
  
            <!--************************************
                    Header Start
            *************************************-->
            <nav id="bt-nav" class="bt-nav">
					<a class="bt-btntogglemenu" href="javascript:void(0);">X</a>
					<div id="bt-navigation" class="bt-navigation">
						<strong class="bt-logo"><a href="index.html"><img class="g" src="{% static 'images/whitelogo.png' %}" alt="image description"></a></strong>
						<ul class="bt-menu">
							{% block home1 %}
							<li class="bt-hasdropdown">
								<a id="home" href="{% url 'home' %}">Home</a>
							</li>
							{% endblock %}
							{% block events1 %}
							<li class="bt-hasdropdown">
								<a id="events" href="{% url 'events' %}">Events</a>
							</li>
							{% endblock %}
							{% if user.is_authenticated %}
							{% block profile1 %}
							<li class="bt-hasdropdown">
								<a id="profile" href="{% url 'profile' %}">Profile</a>
							</li>
							{% endblock %}
							{% endif %}
							{% block about1 %}
							<li class="bt-hasdropdown">
								<a id="about" href="{% url 'about' %}">About Us</a>
							</li>
							{% endblock %}
							{% block contact1 %}
							<li class="bt-hasdropdown">
								<a id="contact" href="{% url 'contact' %}">Contact Us</a>
							</li>
							{% endblock %}
							{% if user.is_authenticated %}
							{% block logout1 %}
							<li class="bt-hasdropdown">
								<a id="logout" href="{% url 'register:auth_logout' %}">Logout</a>
							</li>
							{% endblock %}
							{% else %}
							{% block login1 %}
							<li class="bt-hasdropdown">
								<a id="login" href="{% url 'register:auth_login' %}">Login</a>
							</li>
							{% endblock %}
							{% block signup1 %}
							<li class="bt-hasdropdown">
								<a id="signup" href="{% url 'register:registration_register' %}">SignUp</a>
							</li>
							{% endblock %}
							{% endif %}
						</ul>
						<ul class="bt-socialicons">
							<li><a href="#"><i class="fa fa-facebook"></i></a></li>
							<li><a href="#"><i class="fa fa-twitter"></i></a></li>
							<li><a href="#"><i class="fa fa-instagram"></i></a></li>
						</ul>
						<ul class="bt-navinfo">
							<li><span>Email </span><a href="info%40tasver.html">info@tasver.com</a></li>
							<li><span>Phone +49 900 234 55 - 6</span></li>
							<li><address>Manhatta Hall Advisor Ltd 1258, Melbourne, australia</address></li>
						</ul>
					</div>
				</nav>
				 {% block header %}
				<header id="bt-header" class="bt-header bt-headervfour bt-headerinnerpage bt-headerinnerpagev1 bt-haslayout">
					<div class="container-fluid">
				{% endblock %}
						<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
							<strong class="bt-logo"><a href="#">{% block logo %}<img src="{% static 'images/whitelogo.png' %}" alt="image description">{% endblock %}</a></strong>
							<div class="bt-navigationarea">
								<ul>
									{% block home %}
									<li class="bt-hasdropdown">
										<a  href="{% url 'home' %}">Home</a>
									</li>
									{% endblock %}
									{% block events %}
									<li class="bt-hasdropdown">
										<a href="{% url 'events' %}">Events</a>
									</li>
									{% endblock %}
									{% if user.is_authenticated %}
									{% block profile %}
									<li class="bt-hasdropdown">
										<a href="{% url 'profile' %}">Profile</a>
									</li>
									{% endblock %}
									{% endif %}
									{% block about %}
									<li class="bt-hasdropdown">
										<a href="{% url 'about' %}">About Us</a>
									</li>
									{% endblock %}
									{% block contact %}
									<li class="bt-hasdropdown">
										<a href="{% url 'contact' %}">Contact Us</a>
									</li>
									{% endblock %}
									{% if user.is_authenticated %}
									{% block logout %}
									<li class="bt-hasdropdown">
										<a href="{% url 'register:auth_logout' %}">Logout</a>
									</li>
									{% endblock %}
									{% else %}
									{% block login %}
									<li class="bt-hasdropdown">
										<a href="{% url 'register:auth_login' %}">Login</a>
									</li>
									{% endblock %}
									{% block signup %}
									<li class="bt-hasdropdown">
										<a href="{% url 'register:registration_register' %}">SignUp</a>
									</li>
									{% endblock %}
									{% endif %}
									{% block icon %}
									<li><a class="bt-btntogglemenu" href="javascript:void(0);"><img src="{% static 'images/icons/icon-01.png' %}" alt="image description"></a></li>
									{% endblock %}
								</ul>
							</div>
						</div>
					</div>
				</header>
            <!--************************************
                    Header End
            *************************************-->
        
{% block a %}
{% endblock %}
{% block footer %}
        <!--************************************
				Footer Start
		*************************************-->
		<footer id="bt-footer" class="bt-footer bt-footerborder bt-haslayout">
			<div class="container">
				<div class="row">
					<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
						{% block newsletter %}
						<div class="bt-newsletter">
							<div class="col-xs-12 col-sm-7 col-md-7 col-lg-7">
								<h3>Newsletter</h3>
								<div class="bt-description">
									<p>Latest Photos from Tasver Get alert for new Photoshoot</p>
								</div>
							</div>
							<div class="col-xs-12 col-sm-5 col-md-5 col-lg-5">
								<form class="bt-formtheme bt-formnewsletter">
									<fieldset>
										<input type="email" name="email" class="form-control" placeholder="Enter your E-mail">
										<button type="submit"><i class="icon-email2"></i></button>
									</fieldset>
								</form>
							</div>
						</div>
						{% endblock %}
						<div class="bt-instagramgallery">
							<ul>
								<li>
									<figure><a href="{% static 'images/instagram/img-01.jpg' %}" data-rel="prettyPhoto[instagramphotos]"><img src="{% static 'images/instagram/img-01.jpg' %}" alt="image description"></a></figure>
									<figure><a href="{% static 'images/instagram/img-05.jpg' %}" data-rel="prettyPhoto[instagramphotos]"><img src="{% static 'images/instagram/img-05.jpg' %}" alt="image description"></a></figure>
								</li>
								<li>
									<figure><a href="{% static 'images/instagram/img-02.jpg' %}" data-rel="prettyPhoto[instagramphotos]"><img src="{% static 'images/instagram/img-02.jpg' %}" alt="image description"></a></figure>
									<figure><a href="{% static 'images/instagram/img-06.jpg' %}" data-rel="prettyPhoto[instagramphotos]"><img src="{% static 'images/instagram/img-06.jpg' %}" alt="image description"></a></figure>
									<figure><a href="{% static 'images/instagram/img-08.jpg' %}" data-rel="prettyPhoto[instagramphotos]"><img src="{% static 'images/instagram/img-08.jpg' %}" alt="image description"></a></figure>
								</li>
								<li>
									<figure><a href="{% static 'images/instagram/img-03.jpg' %}" data-rel="prettyPhoto[instagramphotos]"><img src="{% static 'images/instagram/img-03.jpg' %}" alt="image description"></a></figure>
									<figure><a href="{% static 'images/instagram/img-07.jpg' %}" data-rel="prettyPhoto[instagramphotos]"><img src="{% static 'images/instagram/img-07.jpg' %}" alt="image description"></a></figure>
								</li>
								<li><figure><a href="{% static 'images/instagram/img-04.jpg' %}" data-rel="prettyPhoto[instagramphotos]"><img src="{% static 'images/instagram/img-04.jpg' %}" alt="image description"></a></figure></li>
							</ul>
							<div class="bt-instagrambox">
								<i><img src="{% static 'images/icons/icon-02.png' %}" alt="image description"></i>
								<span>@tasver</span>
								<a class="bt-btn bt-btnblack bt-btn-lg" href="javascript:void(0);"><span>folloe now</span></a>
							</div>
						</div>
						<div class="bt-footerbar">
							<div class="bt-navandcopyright">
								<nav class="bt-addnav">
									<ul>
										<li><a href="#">Home</a></li>
										<li><a href="#">FAQ</a></li>
										<li><a href="#">TERMS OF SERVICES</a></li>
										<li><a href="#">PRIVACY &amp; COOKIES</a></li>
										<li><a href="#">CONTACT Us</a></li>
									</ul>
								</nav>
								<span class="bt-copyright">Copyrights 2017 Tasver. All rights reserved</span>
							</div>
							<div class="bt-followus">
								<span>follow us</span>
								<ul class="bt-socialicons">
									<li><a href="javascript:void(0);"><i class="fa fa-facebook"></i></a></li>
									<li><a href="javascript:void(0);"><i class="fa fa-twitter"></i></a></li>
									<li><a href="javascript:void(0);"><i class="fa fa-instagram"></i></a></li>
									<li><a href="javascript:void(0);"><i class="fa fa-google-plus"></i></a></li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</footer>
		<!--************************************
				Footer End
		*************************************-->
	</div>
	{% endblock %}
	{% block script %}
	{% endblock %}
	{% block jquery-library %}
	<script src="{% static 'js3/vendor/jquery-library.js' %}"></script>
	{% endblock %}
	<script src="{% static 'js3/vendor/bootstrap.min.js' %}"></script>
	<script src="{% static 'js3/jquery.cubeportfolio.min.js' %}"></script>
	<script src="{% static 'js3/tinycolor-0.9.16.min.js' %}"></script>
	<script src="{% static 'js3/jquery.scrollTo.min.js' %}"></script>
	<script src="{% static 'js3/jquery.pogoslider.js' %}"></script>
	<script src="{% static 'js3/touchswipe.min.js' %}"></script>
	<script src="{% static 'js3/jgallery.min.js' %}"></script>
	<script src="{% static 'js3/jquery.vide.js' %}"></script>
	<script src="{% static 'js3/prettyPhoto.js' %}"></script>
	<script src="{% static 'js3/slick.min.js' %}"></script>
	<script src="{% static 'js3/parallax.js' %}"></script>
	<script src="{% static 'js3/countTo.js' %}"></script>
	<script src="{% static 'js3/appear.js' %}"></script>
	{% block theme %}
	<script src="{% static 'js3/themefunction.js' %}"></script>
	{% endblock %}
</body>

<!-- Mirrored from wahabali.com/work/tasver/index2.html by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 09 Sep 2017 09:06:03 GMT -->
</html>

templates/body.html
    {% load staticfiles %}
    <style type="text/css">
          
  input[type="text"],input[type="email"]
   {
     text-transform: lowercase;
   }
        
        body{
    text-align: center;
	font-family: 'Roboto', sans-serif;
    background:url("{% static 'images/1.jpg' %}")no-repeat 0px 0px;
	-webkit-background-size:cover; 
	-moz-background-size:cover;  
	background-size:cover; 
	min-height:700px;
    }
    .bt-newsletter,.bt-instagramgallery
{
    margin-top: 10em;
}
    </style>
<main id="bt-main" class="bt-main bt-haslayout">